In [599]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [600]:
def loss_function(res, pred):
    return (pred[0] - res) ** 2 + (pred[1] - abs(res - 1)) ** 2

def aggregate(res, pred, loss_func = loss_function, weights = None):
    T = len(res)
    K = len(pred)
    if not weights:
        weights = np.full(K, 1/K)
    agg_pred = np.zeros(2 * T).reshape(T, 2)
    for t in range(1, T):
        gamma = pred[:,t]
        def G(omega):
            return -np.log(np.inner(weights, np.exp(-loss_func(omega, np.transpose(gamma)))))
        s = 2
        s1 = (G(0) + G(1)) / 2 + 1
        s2 = (G(0) + G(1)) / 2 - 1
        if s1 > G(0) and s1 > G(1):
            s = s1
        if s2 < G(0) and s2 < G(1):
            s = s2
        weights = (weights * np.exp(-loss_func(res[t], np.transpose(gamma)))) / np.sum(weights)
        agg_pred[t] = np.array([abs(s - G(0)) / 2, abs(s - G(1)) / 2])
        agg_pred[t] = agg_pred[t] / np.sum(agg_pred[t])
    return agg_pred


    

In [601]:
df = pd.read_pickle('matches.pkl')

In [602]:
res = np.array(df[df['k1'].notna()]['player1_win'])
k1 = 1 / np.array(df[df['k1'].notna()]['k1'])
k2 = 1 - k1
cfs = np.transpose([k1, k2])
r1 = np.random.rand(len(k1))
r2 = 1 - r1
rand_pred = np.transpose(np.array([r1, r2]))
pred = np.array([rand_pred, cfs])

In [603]:
cfs

array([[0.29411765, 0.70588235],
       [0.92592593, 0.07407407],
       [0.11111111, 0.88888889],
       ...,
       [0.42194093, 0.57805907],
       [0.58139535, 0.41860465],
       [0.60240964, 0.39759036]])

In [604]:
aggregate(res, pred)

array([[0.        , 0.        ],
       [0.64126025, 0.35873975],
       [0.0529288 , 0.9470712 ],
       ...,
       [0.45036309, 0.54963691],
       [0.61932088, 0.38067912],
       [0.60604744, 0.39395256]])

In [605]:
res = np.array(df[df['k1'].notna()]['player1_win'])
k1 = 1 / np.array(df[df['k1'].notna()]['k1'])
k2 = 1 - k1
cfs = np.transpose([k1, k2])
r1 = np.random.rand(len(k1))
r2 = 1 - r1
rand_pred = np.transpose(np.array([r1, r2]))
magic_predict_1 =  res
magic_predict_2 = abs(res - 1)
magic_predict = np.transpose(np.array([magic_predict_1, magic_predict_2]))
pred = np.array([magic_predict, cfs, rand_pred])
#bug with exelent prediction?

In [606]:
aggregate(res, pred)

array([[0.        , 0.        ],
       [0.96175096, 0.03824904],
       [0.05669099, 0.94330901],
       ...,
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.        , 1.        ]])

In [614]:
res = np.array(df[df['k1'].notna()]['player1_win'])
k1 = 1 / np.array(df[df['k1'].notna()]['k1'])
k2 = 1 - k1
cfs = np.transpose([k1, k2])
r1 = np.random.rand(len(k1))
r2 = 1 - r1
rand_pred = np.transpose(np.array([r1, r2]))
magic_predict_1 =  abs(res - 0.01)
magic_predict_2 = abs(res - 0.99)
magic_predict = np.transpose(np.array([magic_predict_1, magic_predict_2]))
pred = np.array([magic_predict, cfs, rand_pred])


In [615]:
aggregate(res, pred)

array([[0.        , 0.        ],
       [0.80414753, 0.19585247],
       [0.24420169, 0.75579831],
       ...,
       [0.99      , 0.01      ],
       [0.99      , 0.01      ],
       [0.99      , 0.01      ]])

In [607]:
res

array([0, 1, 0, ..., 1, 1, 1], dtype=int64)